#!/bin/bash

# copies contents of file to clipboard
# clipcp - clipboard copy

SCRIPT_NAME="clipcp"
VERSION="1.0"
OPTS=$(getopt -o vh \
	--long version \
	--long help \
	-- "$@")
eval set -- "$OPTS"


while true
do
	case "$1" in
		-h|--help)
			echo -e "Usage: $SCRIPT_NAME [OPTION]... FILE\n"
			echo -e "Copy contents of the file to the system's clipboard.\n"
			echo "List of possible options:"
			echo -e "\t-v, --version\tshow version info"
			echo -e "\t-h, --help\tprint this help"
			exit;;
		-v|--version)
			echo "$SCRIPT_NAME (script) $VERSION"
			echo "Written by Hubert Obrzut"
			exit;;
		--) shift; break;;
	esac
	shift
done

[ -z "$1" ] && exit 1
[ -e "$1" ] || exit 1

cat "$1" | xclip -selection clipboard
